shop/urls.py
from django.contrib import admin
from django.urls import path, include
from shop import views

urlpatterns = [
    path('shopping-cart', views.cart, name='cart'),
    path('shopping-cart/<slug:slug>/add', views.add_travel_to_cart, name='add_travel_to_cart'),
    path('shopping-cart/<slug:slug>/remove', views.remove_travel_to_cart, name='remove_travel_to_cart'),
    path('checkout', views.checkout, name='checkout'),
    path('payment-hook', views.payment_completed_hook, name='payment_hook'),
]

travelagency/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('accounts/', include('accounts.urls')),
    path('travels/', include('travels.urls')),
    path('', include('shop.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

travels/urls.py
from django.contrib import admin
from django.urls import path, include
from travels import views

urlpatterns = [
    path('', views.travels, name='travels'),
    path('<slug:slug>', views.travel, name='travel'),
]

travels/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User
from django.shortcuts import reverse

COUNTRY_CHOICES = (
    ('M', 'Mexique'),
    ('C', 'Cuba'),
    ('RP', 'République dominicaine')
)

class Destination(models.Model):
    hotel_name = models.CharField(max_length=200)
    country = models.CharField(choices=COUNTRY_CHOICES, max_length=2)
    picture = models.ImageField(upload_to='pictures/destinations/', blank=True)
    description = models.TextField(blank=True, null=True)

    def __str__(self):
        return self.hotel_name

class Travel(models.Model):
    name = models.CharField(max_length=200)
    destination = models.ForeignKey(Destination, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=6, decimal_places=2)
    start_day = models.DateField()
    end_day = models.DateField()
    slug = models.SlugField()

    """def get_absolute_url(self, slug):
        return reverse('travels', kwargs={'slug': self.slug})"""

    def __str__(self):
        return self.name

    def generate_slug(self): #FIXME: Valider qu'il n'y aura pas de doublon d'adresse
        return slugify(self.destination.name)

    """ Génère automatiquement un slug
    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Travel, self).save(*args, **kwargs)
    """

class OrderTravel(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    travel = models.ForeignKey(Travel, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    ordered = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.quantity} de {self.travel.name}"

    def get_total_travel_price(self):
        return self.quantity * self.travel.price


class Order(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    ref_code = models.CharField(max_length=20, blank=True, null=True)
    travels = models.ManyToManyField(OrderTravel)
    ordered = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    def get_total_price(self):
        total = 0
        for travel in self.travels.all():
            total += travel.get_total_travel_price()
        return total

travels/views.py
from django.shortcuts import render
from travels.models import Travel, Destination

def travels(request):
    travels = Travel.objects.all()

    context = {
        'travels' : travels
    }

    return render(request, 'travels/travels.html', context)

def travel(request, slug):

    travel = Travel.objects.get(slug=slug)

    context = { 'travel' : travel }

    return render(request, 'travels/travel.html', context)

templates/travels/travel.html
{% extends 'base.html' %}

{% load humanize %}

{% block content %}
  <!--Grid row-->
  <div class="row wow fadeIn mt-3">

    <!--Grid column-->
    <div class="col-md-6 mb-4">

      <img src="{{ travel.destination.picture.url }}" class="img-fluid" alt="{{ travel.slug }}">

    </div>
    <!--Grid column-->

    <!--Grid column-->
    <div class="col-md-6 mb-4">

      <!--Content-->
      <div class="p-4">

        <div class="mb-3">
          <a href="">
            <span class="badge purple mr-1">{{ travel.destination.get_country_display }}</span>
          </a>
        </div>

        <p class="lead">
          <!--<span class="mr-1">
            <del>$200</del>
          </span> -->
          <span>{{ travel.price|intcomma }} $</span>
        </p>

        <p class="lead font-weight-bold">Description</p>

        <p>{{ travel.destination.description }}</p>

        <form class="d-flex justify-content-left" method="POST" action="{% url 'cart' %}">
          {% csrf_token %}
          <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px" name="quantity">
          <input type="hidden" value="{{ travel.slug }}" name="travel_slug">
          <button class="btn btn-primary btn-md my-0 p" type="submit">Ajouter au panier
            <i class="fas fa-shopping-cart ml-1"></i>
          </button>

        </form>

      </div>
      <!--Content-->

    </div>
    <!--Grid column-->

  </div>
  <!--Grid row-->
{% endblock content %}

templates/travels/travels.html
{% extends 'base.html' %}
{% load humanize %}

{% block content %}
<h1 class="mt-4 mb-3">Voyages</h1>

<div class="row row-cols-1 row-cols-md-2">
    {% for travel in travels %}
    <div class="col mb-4">
        <!-- Card -->
<div class="card">

    <!-- Card image -->
    <div class="view overlay">
      <img class="card-img-top" src="{{travel.destination.picture.url}}"
        alt="Card image cap">
      <a href="{% url 'travel' travel.slug %}">
        <div class="mask rgba-white-slight"></div>
      </a>
    </div>
  
    <!-- Card content -->
    <div class="card-body">
  
      <!-- Title -->
      <h4 class="card-title">{{ travel.destination.hotel_name }}</h4>
      <!-- Text -->
      <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's
        content.</p>
      <!-- Button -->
      <a href="{% url 'travel' travel.slug %}" class="btn btn-primary">{{ travel.price|intcomma }} $</a>
  
    </div>
  
  </div>
  <!-- Card -->
    </div>
    {% endfor %}
    
</div>

<div class="row">
<div class="col">
      <!--Pagination-->
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">
    
          <!--Arrow left-->
          <li class="page-item disabled">
            <a class="page-link" href="#" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
    
          <li class="page-item active">
            <a class="page-link" href="#">1
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="page-item">
            <a class="page-link" href="#">2</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="#">3</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="#">4</a>
          </li>
          <li class="page-item">
            <a class="page-link" href="#">5</a>
          </li>
    
          <li class="page-item">
            <a class="page-link" href="#" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
        </ul>
      </nav>
      <!--Pagination-->
</div>
</div>
  
{% endblock content %}